language: rust
rust:
  - nightly
  
before_script: |
  rustup component add rustfmt-preview &&
  rustup component add clippy-preview --toolchain=nightly
  # run a wasm-pack build to make sure we can still compile to wasm
  # cargo install wasm-pack
  # wasm-pack init 
script: |
  rustup target add wasm32-unknown-unknown
  cargo check --target wasm32-unknown-unknown
  cargo fmt --all -- --check &&
  cargo clippy -- -D all &&
  cargo build --verbose &&
  cargo test  --verbose
cache: cargo
