[package]
name = "mongodb-schema-parser"
version = "0.1.0"
license = "Apache-2.0"
repository = "https://github.com/lrlna/mongodb-schema-parser"
documentation = "https://docs.rs/mongodb-schema-parser"
description = "MongoDB Schema Analysis"
authors = ["Irina Shestak <shestak.irina@gmail.com>"]
readme = "README.md"
edition = "2018"

[dependencies]
failure = "0.1.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
bson = "0.12.2"
mongodb = "0.3.10"

[dependencies.wasm-bindgen]
version = "^0.2"
features = ["serde-serialize"]

[dev-dependencies]
bson = "0.12.1"
mongodb = "0.3.9"
